### ISSUE TITLE
Select yanked scripts

### ISSUE THREAD

**Issue by ikeasamoahansah** [ikeasamoahansah/clipboard.nvim#1] opened 2024-10-04 22:25 UTC
Currently, you can only view yanked scripts, make it so that you can select them as well

**Comment by JohananOppongAmoateng** [comment] 2024-10-07 05:16
@ikeasamoahansah assign to me

**Comment by ikeasamoahansah** [comment] 2024-10-07 08:39
@JohananOppongAmoateng you can go ahead and submit a PR

**Comment by Aliqyan-21** [comment] 2024-10-08 09:43
@ikeasamoahansah can I work on it if the issue is still open?

**Comment by JohananOppongAmoateng** [comment] 2024-10-08 10:23
@Aliqyan-21 I am working on it will push the code today

**Comment by ikeasamoahansah** [comment] 2024-10-08 17:10
#2 closed this

**Closed as completed** 2024-10-08 17:09 UTC
Labels: good first issue, hacktoberfest
